/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author alebel
 */
public class MenuWindow extends javax.swing.JDialog {

    /**
     * Creates new form MenuWindow
     */
    public MenuWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public MenuWindow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info1Label = new javax.swing.JLabel();
        info2Label = new javax.swing.JLabel();
        info3Label = new javax.swing.JLabel();
        primWeapLabel = new javax.swing.JLabel();
        secondWeapLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        currLevelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Character Menu");
        setLocationByPlatform(true);
        setModal(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(462, 398));
        setSize(new java.awt.Dimension(500, 300));

        info1Label.setForeground(new java.awt.Color(240, 0, 0));
        info1Label.setText("Info1:");

        info2Label.setForeground(new java.awt.Color(240, 0, 0));
        info2Label.setText("Info2:");

        info3Label.setForeground(new java.awt.Color(240, 0, 0));
        info3Label.setText("Info3:");

        primWeapLabel.setForeground(new java.awt.Color(240, 0, 0));
        primWeapLabel.setText("Primary Weapon:");

        secondWeapLabel.setForeground(new java.awt.Color(240, 0, 0));
        secondWeapLabel.setText("Secondary Weapon:");

        okButton.setBackground(new java.awt.Color(120, 120, 120));
        okButton.setForeground(new java.awt.Color(240, 0, 0));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        currLevelLabel.setForeground(new java.awt.Color(240, 0, 0));
        currLevelLabel.setText("Current Level: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primWeapLabel)
                            .addComponent(secondWeapLabel)
                            .addComponent(info3Label)
                            .addComponent(info2Label)
                            .addComponent(info1Label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(currLevelLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(currLevelLabel)
                .addGap(26, 26, 26)
                .addComponent(info1Label)
                .addGap(27, 27, 27)
                .addComponent(info2Label)
                .addGap(28, 28, 28)
                .addComponent(info3Label)
                .addGap(31, 31, 31)
                .addComponent(primWeapLabel)
                .addGap(28, 28, 28)
                .addComponent(secondWeapLabel)
                .addGap(37, 37, 37)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling ce here:
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuWindow dialog = new MenuWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currLevelLabel;
    private javax.swing.JLabel info1Label;
    private javax.swing.JLabel info2Label;
    private javax.swing.JLabel info3Label;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel primWeapLabel;
    private javax.swing.JLabel secondWeapLabel;
    // End of variables declaration//GEN-END:variables
}
