/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.swingcomponents;

import controller.GameController;
import view.gameobjects.Hero;
/**
 *
 * @author Tyrel Tachibana-sama
 */
public class DeathScreen extends javax.swing.JDialog {

    /**
     * Creates new form MenuWindow
     */
    public DeathScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DeathScreen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info1Label = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();
        currLevelLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        currLevelLabel1 = new javax.swing.JLabel();
        currLevelLabel2 = new javax.swing.JLabel();
        currLevelLabel3 = new javax.swing.JLabel();
        highScoresButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();
        worldMapButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Death Happens, probably becuase you suck.");
        setLocationByPlatform(true);
        setModal(true);
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 300));

        info1Label.setForeground(new java.awt.Color(240, 0, 0));
        info1Label.setText("Enter name for the records: ");

        mainMenuButton.setBackground(new java.awt.Color(120, 120, 120));
        mainMenuButton.setForeground(new java.awt.Color(240, 0, 0));
        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        currLevelLabel.setForeground(new java.awt.Color(240, 0, 0));
        currLevelLabel.setText("You are dead!");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        currLevelLabel1.setForeground(new java.awt.Color(240, 0, 0));
        currLevelLabel1.setText("你死了!");

        currLevelLabel2.setForeground(new java.awt.Color(240, 0, 0));
        currLevelLabel2.setText("あなたが死んでいる!");

        currLevelLabel3.setForeground(new java.awt.Color(240, 0, 0));
        currLevelLabel3.setText("당신은 죽은!");

        highScoresButton.setBackground(new java.awt.Color(120, 120, 120));
        highScoresButton.setForeground(new java.awt.Color(240, 0, 0));
        highScoresButton.setText("High Scores");
        highScoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoresButtonActionPerformed(evt);
            }
        });

        restartButton.setBackground(new java.awt.Color(120, 120, 120));
        restartButton.setForeground(new java.awt.Color(240, 0, 0));
        restartButton.setText("Restart Level");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        worldMapButton.setBackground(new java.awt.Color(120, 120, 120));
        worldMapButton.setForeground(new java.awt.Color(240, 0, 0));
        worldMapButton.setText("World Map");
        worldMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worldMapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currLevelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currLevelLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currLevelLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(info1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highScoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(restartButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(worldMapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(currLevelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currLevelLabel1)
                .addGap(9, 9, 9)
                .addComponent(currLevelLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currLevelLabel3)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info1Label)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(worldMapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(highScoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        controller.GameController.getInstance().showMainMenu();
        Hero.dead = false;
        this.dispose();
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void highScoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoresButtonActionPerformed
        controller.GameController.getInstance().showScores();
        Hero.dead = false;
        this.dispose();
    }//GEN-LAST:event_highScoresButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_restartButtonActionPerformed
        switch (GameController.currentLevel) {
            case 1:
                controller.GameController.getInstance().showLevel1();
                Hero.dead = false;        
                this.dispose();
                break;
            case 2:
                controller.GameController.getInstance().showLevel2();
                Hero.dead = false;
                this.dispose();
                break;
            case 3:
                controller.GameController.getInstance().showLevel3();
                Hero.dead = false;
                this.dispose();
                break;
            case 4:
                controller.GameController.getInstance().showLevel4();
                Hero.dead = false;
                this.dispose();
                break;
            case 5:
                controller.GameController.getInstance().showLevel5();
                Hero.dead = false;
                this.dispose();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_restartButtonActionPerformed

    private void worldMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worldMapButtonActionPerformed
        controller.GameController.getInstance().showWorld();
        Hero.dead = false;
        this.dispose();
    }//GEN-LAST:event_worldMapButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeathScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeathScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeathScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeathScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeathScreen dialog = new DeathScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });

                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currLevelLabel;
    private javax.swing.JLabel currLevelLabel1;
    private javax.swing.JLabel currLevelLabel2;
    private javax.swing.JLabel currLevelLabel3;
    private javax.swing.JButton highScoresButton;
    private javax.swing.JLabel info1Label;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton restartButton;
    private javax.swing.JButton worldMapButton;
    // End of variables declaration//GEN-END:variables
}
